### ISSUE TITLE
Permission to use config in ciscoconfparse2 GPLv3

### ISSUE THREAD

**Issue by mpenning** [sjhloco/sdwan_bgp_lab#1]
Hello Steve,

I have a python [cisco config parsing library][1] that uses the GPLv3 license.  I noticed that you have a great config that I could use to test some new capabilities I added to the parsing library, but I would like to be sure that you're ok with me releasing the config below under a GPLv3 license since you don't have an explicit license associated with this git repo at the moment.

If you don't want me to include the config in my repo that's fine... I can fake the data based off the configs you have, but it's quite a bit easier if I don't fake the data.

The config in question is your vEdge config here:
https://github.com/sjhloco/sdwan_bgp_lab/blob/main/S11-cEdge01.txt

Please let me know whether you are or are not ok with me including it verbatim in my [ciscoconfparse2][1] config parsing package.

Thank you,
\mike

  [1]: https://github.com/mpenning/ciscoconfparse2

**Comment by sjhloco** [comment]
Hey Mike, Appreciate you asking, sure no worries use what you need. Good to know that something maybe useful to someone other than myself for once 😀
